## NumPy Basics

#### NumPy is a fundamental package for scientific computing in Python.
- It provides support for large multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

#### Importing NumPy
- NumPy is usually imported under the alias 'np'.

In [16]:
import numpy as np

#### Creating Arrays
- NumPy arrays can be created from Python lists or tuples using the array() function.

In [18]:
array_from_list = np.array([1, 2, 3, 4, 5])
print(array_from_list)

[1 2 3 4 5]


In [17]:
# Creating arrays with specific values
zeros_array = np.zeros(5)  # Array of zeros
ones_array = np.ones(5)  # Array of ones
full_array = np.full(5, 7)  # Array of sevens
print(zeros_array, ones_array, full_array)

[0. 0. 0. 0. 0.] [1. 1. 1. 1. 1.] [7 7 7 7 7]


In [ ]:
# Practice Questions:
# 1. Create a NumPy array from a list of numbers [10, 20, 30, 40, 50].
# 2. Create a NumPy array of ten zeros.
# 3. Create a NumPy array of five ones.

In [5]:
import numpy as np
array_list = np.array([10, 20, 30, 40, 50])
array_zeros = np.zeros(10)
array_ones = np.ones(5)
print(array_list, array_zeros, array_ones)

[10 20 30 40 50] [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [1. 1. 1. 1. 1.]


In [6]:
array_empty = np.empty(shape = (2,3))
array_empty

array([[6.23042070e-307, 1.33512376e-306, 1.11261230e-306],
       [7.56577399e-307, 9.34600963e-307, 1.05699581e-307]])

In [24]:
# zeros
array_0s = np.zeros(shape  = (2,3))
print(array_0s)

array_0s = np.zeros(shape = (2,3), dtype = np.int8) 
print('\n',array_0s)

[[0. 0. 0.]
 [0. 0. 0.]]

 [[0 0 0]
 [0 0 0]]


In [6]:
# ones
array_1s = np.ones(shape  = (2,3), dtype = np.int8)
print('\n',array_1s)


 [[1 1 1]
 [1 1 1]]


In [26]:
# full
array_full = np.full(shape = (2,3), fill_value = 2) 
# One additional mandatory argument - fill_value -> scalar
array_full

array([[2, 2, 2],
       [2, 2, 2]])

In [8]:
array_full = np.full(shape = (2,3), fill_value = 'Three-Six-Five')
array_full

array([['Three-Six-Five', 'Three-Six-Five', 'Three-Six-Five'],
       ['Three-Six-Five', 'Three-Six-Five', 'Three-Six-Five']],
      dtype='<U14')

In [28]:
matrix_A = np.array([[1,0,9,2,2],[3,23,4,5,1],[0,2,3,4,1]])
matrix_A

array([[ 1,  0,  9,  2,  2],
       [ 3, 23,  4,  5,  1],
       [ 0,  2,  3,  4,  1]])

In [29]:
array_empty_like = np.empty_like(matrix_A)    

# Shape and type are like the prototype. 
# If we want to override this, we can define dtype and shape and pass different values (but why even use empty_like then). 

print(array_empty_like)

[[      0       0       0       0       0]
 [      0       0       0       0       0]
 [   1884       0       0 6357091       0]]


In [30]:
array_0s_like = np.zeros_like(matrix_A)    
print(array_0s_like)

# We have corresponding functions for 1s and full as well.

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [49]:
# Practice questions:
# 1. Generate 4 arrays of size 10:
# A) The first one should be "empty"
# B) The second one should be full of 0s
# C) The third one should be full of 1s
# D) The last one should be full of 2s

# 2. Generate 4 more arrays. This time, they should be 2 by 4 arrays

In [13]:
import numpy as np
array_four = np.full(10, 4)
array_empty = np.empty(shape =(4, 3))
full_of_zeros = np.full(shape = (3, 5), fill_value = 0)
full_of_ones = np.full(shape = (2, 5), fill_value = 1)
full_of_twos = np.full(shape = (3, 2), fill_value = 2)
array_fours = np.full(shape = (2, 4), fill_value = 10, dtype = np.int8)
print("\n", array_four, array_empty, full_of_zeros, full_of_ones, full_of_twos, array_fours)


 [4 4 4 4 4 4 4 4 4 4] [[1.19540586e-311 2.47032823e-322 0.00000000e+000]
 [0.00000000e+000 1.08221785e-312 8.75983079e+164]
 [5.45118365e-090 1.56082890e+161 1.53471084e-052]
 [2.77235459e+180 3.99910963e+252 4.46786204e-062]] [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] [[1 1 1 1 1]
 [1 1 1 1 1]] [[2 2]
 [2 2]
 [2 2]] [[10 10 10 10]
 [10 10 10 10]]


### Generating Data with NumPy

- Creating arrays with arange() and linspace()
- The arange() function generates an array with a range of values.


In [15]:
#range(30)
list(range(30))

# range(30) results in a range object.
# list(range(30)) creates a list with all the values in this range.

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

In [14]:
array_rng = np.arange(30)
array_rng

## Creates an ndarray with the values in this range.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
range_array = np.arange(0, 10, 2)  # Start, stop, step
print(range_array)  # Output: [0, 2, 4, 6, 8]

In [16]:
array_rng = np.arange(start = 0, stop =  30, step = 2.5)
array_rng

# "Step" doesn't have to be the same type as the values of the array. 

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ,
       27.5])

In [39]:
array_rng = np.arange(start = 0, stop =  30, step = 2.5, dtype = np.float32)
# array_rng = np.arange(start = 0, stop =  30, step = 2.5, dtype = np.int32)
array_rng

# The casting happens after all the computations. 

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ,
       27.5], dtype=float32)

In [ ]:
# The linspace() function generates an array with evenly spaced values.
linspace_array = np.linspace(0, 1, 5)  # Start, stop, number of points
print(linspace_array)  # Output: [0., 0.25, 0.5, 0.75, 1.]

In [17]:
# Generating random numbers
random_array = np.random.random((2, 3))  # 2x3 array of random numbers between 0 and 1
print(random_array)

[[0.30513266 0.94747254 0.47772368]
 [0.10287732 0.88080836 0.44732652]]


In [18]:
# Create a 5x5 array of random integers between 0 and 100
randint_array = np.random.randint(0, 100, size=(3, 5))
randint_array

array([[ 6, 35, 82, 80, 60],
       [21, 51, 88, 17, 94],
       [95, 59, 92, 92, 68]])

In [ ]:
# Practice Questions:
# 1. Create an array of numbers from 0 to 20 with a step of 5 using arange().
# 2. Create an array of 10 numbers evenly spaced between 0 and 1 using linspace().
# 3. Generate a 3x3 array of random numbers between 0 and 1.

In [20]:
import numpy as np
array_range = np.arange(0, 20, 5)
array_linspace = np.linspace(0, 1, 10)
array_random = np.random.random((3, 3))

print(array_range, array_linspace, array_random)

[ 0  5 10 15] [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ] [[0.95840488 0.74909452 0.76775047]
 [0.66279269 0.61971378 0.58132598]
 [0.26846662 0.29495733 0.71324374]]


## NumPy Fundamentals

#### Array Attributes
- NumPy arrays have attributes such as shape, size, and ndim.

In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # Output: (2, 3)
print(arr.size)  # Output: 6
print(arr.ndim)  # Output: 2

(2, 3)
6
2


#### Array Indexing and Slicing
- You can index and slice NumPy arrays just like Python lists.

In [32]:
print(arr)
print(arr[0, 1])  # Output: 2 (element at row 0, column 1)
print(arr[:, 2])  # Output: [2, 5] (all rows, column 1)
print(arr[1, :])  # Output: [4, 5, 6] (row 1, all columns)

[[1 2 3]
 [4 5 6]]
2
[3 6]
[4 5 6]


In [18]:
print(arr[0,2])

3


In [23]:
print(arr[0,:])

[1 2 3]


In [41]:
print(arr[:,0])

[1 4]


#### Array reshaping

In [29]:
a =np.array([0,0,0,0,1,0,0,0,1,0])
# We can reshape the array in any dimension, to do so we use the NumPy method : reshape.

b = a.reshape(5,2)
print(b)

[[0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 0]]


#### Assigning Values

In [48]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
leye_array = np.array([[2,4,5], [4,67,8]])
leye_array

array([[ 2,  4,  5],
       [ 4, 67,  8]])

In [49]:
# Assign a value to an individual element.
array_a[1,2] = 9
array_a 

array([[1, 2, 3],
       [4, 5, 9]])

In [39]:
# Assign a value to an entire row.
array_a[0] = 9
array_a

array([[9, 9, 9],
       [4, 5, 9]])

In [50]:
# Assign a value to an entire column.
array_a[:,0] = 9
array_a

array([[9, 2, 3],
       [9, 5, 9]])

In [51]:
# Assign different values to an entire row via a list.
list_a = [1,3,8]
array_a[1] = list_a
array_a

array([[9, 2, 3],
       [1, 3, 8]])

In [52]:
# Assign the same value to all the individual elements in the array.
array_a[:] = 9
array_a

array([[9, 9, 9],
       [9, 9, 9]])

In [53]:
array_a = 9
array_a

9

In [54]:
# Practice Questions:

array_1D = np.array([10,11,12,13, 14])

array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])

array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])


# 1. Display the first element (not necessarily individual element) for each of the 3 arrays we defined above

# 2. Call the first individual element of the each of the 3 arrays.

# 3. Uses negative indices to display the last element of each array

#### More on Slicing

In [60]:
matrix_A = np.array([[1,2,3],[4,5,6],[2,5,7]])
matrix_A

array([[1, 2, 3],
       [4, 5, 6],
       [2, 5, 7]])

In [61]:
matrix_A[:]
## The default start and stop for slicing are the origin and the end of the array. 
## Hence, [:] includes the entire array.

array([[1, 2, 3],
       [4, 5, 6],
       [2, 5, 7]])

In [62]:
type(matrix_A[:,:])
## [:,:] -> All rows, and all columns.

numpy.ndarray

In [71]:
matrix_A[:2]
# [:2] -> All the rows up to the 3rd one (excluding the third one).

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
matrix_A[-3:]
# [:-1] -> All the rows up to the last one.

array([[1, 2, 3],
       [4, 5, 6],
       [2, 5, 7]])

In [75]:
matrix_A[:,1:]
# All the rows, but only the columns from the one with index 1 (second column) onwards.

array([[2, 3],
       [5, 6],
       [5, 7]])

In [76]:
matrix_A[1:,1:]
# All the rows after the first one and all the columns after the first one.

array([[5, 6],
       [5, 7]])

#### Stepwise slicing

In [ ]:
matrix_B = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_B

In [ ]:
matrix_B[:,::2]
# The syntax for each dimension is "[start : stop : step]".

In [ ]:
# Practice Questions:

array_1D = np.array([10,11,12,13, 14])

array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])

array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])

# 1. Slice the first column of the 2-D array.
# 2. Slice the last two columns of the 2-nd row of the 2-D array
# 3. Slice the 2-nd row of the 2-D array excluding the last two columns

## Working with Arrays

- Basic Operations
- You can perform element-wise operations on NumPy arrays.
- Element-wise means that whatever mathematical computation we are conducting , we are doing it to each element of the array

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  # Output: [5, 7, 9]
print(a * b)  # Output: [4, 10, 18]
print(a - b)  # Output: [-3, -3, -3]
print(a / b)  # Output: [0.25, 0.4, 0.5]

#### Mathematical Functions
- NumPy provides a variety of mathematical functions.

In [ ]:
print(np.sin(a))  # Output: [0.8415, 0.9093, 0.1411]
print(np.log(a))  # Output: [0., 0.6931, 1.0986]
print(np.sqrt(a))  # Output: [1., 1.4142, 1.7321]

In [ ]:
# Practice Questions:
# 1. Create two NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
# 2. Apply the numpy functions sin(), log(), and sqrt() to a NumPy array.

In [ ]:
array_a = np.array([7,8,9])

array_b = np.array([[1,2,3],[4,5,6]])

#### More operations

In [ ]:
array_b * 2
## Multiplying each element of array_b by 2

In [37]:
list_a = [1,2,3]
list_a + [2]
list_a
## Since lists don't work elementwise, we're concatenating [2] to list_a.

[1, 2, 3]

In [ ]:
array_a + 2
## Element Wise addition adds 2 to each element of array_a.

In [ ]:
array_a * array_b[1]
## Element Wise multiplication. 
## We multiply each individual element of array_a by its corresponding element in the second row of array_b.

In [ ]:
array_b - array_a
## The order of the elements matters for elementwise subtraction, division, as well as other operations. 

In [ ]:
# Practice questions

array_1D = np.array([10,11,12,13, 14])

array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])

array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])

# 1. Add 2 to every element of the 3 arrays without overwriting their values.
# 2. Multiply the values of each array by 100 without overwriting their values.

### Datatypes Supported by Numpy

In [ ]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

In [ ]:
array_a = np.array([[1,2,3],[4,5,6]], dtype = np.float16)
array_a
# Defining all the values as floats (decimals).

In [ ]:
array_a = np.array([[1,2,3],[4,5,6]], dtype = np.complex64)
array_a
# Defining all the values as complex numbers.

In [ ]:
array_a = np.array([[1,2,0],[4,5,6]], dtype = np.bool)
array_a
# Defining all the values as Booleans.

In [ ]:
array_a = np.array([[10,2,3],[4,5,6]], dtype = np.str)
array_a
# Defining all the values as text.

#### Converting Data Type on Existing Arrays
- The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

In [ ]:
arr = np.array([1.1, 2.1, 3.1])
print(arr.dtype)

newarr = arr.astype(int)
print(newarr.dtype)

In [ ]:
# Practice Questions:

array_1D = np.array([10,11,12,13,14])

array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])

array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])


# Alter the code above to re-define the 3 arrays as the following datatypes:

# array_1D -> NumPy Strings
# array_2D -> Complex Numbers
# array_3D -> 64-bit Floats

### Statistics with NumPy

- NumPy provides various statistical functions to analyze data.

In [ ]:
data = np.array([1, 2, 3, 4, 5])

# Mean, median, and standard deviation
mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)
print("Mean:", mean)  # Output: Mean: 3.0
print("Median:", median)  # Output: Median: 3.0
print("Standard Deviation:", std_dev)  # Output: Standard Deviation: 1.4142

In [ ]:
# Sum and cumulative sum
sum_data = np.sum(data)
cumsum_data = np.cumsum(data)
print("Sum:", sum_data)  # Output: Sum: 15
print("Cumulative Sum:", cumsum_data)  # Output: Cumulative Sum: [ 1  3  6 10 15]

In [ ]:
# Practice Questions:
# 1. Create a NumPy array of random numbers and compute the mean, median, and standard deviation.
# 2. Compute the sum and cumulative sum of the array.

#### You can also use the mean function to calculate the mean along a specific axis of a multi-dimensional array using the axis parameter.

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(np.mean(x, axis=0))

#### Minimal and maximal values in numpy :
- In NumPy, there are several functions that can be used to find the minimum value(s) of an array or matrix. These include:

- np.min: This function returns the minimum value of an array or matrix.
- np.amin: This function returns the minimum value of an array or matrix along a given axis.
- np.minimum: This function returns an array or matrix with the element-wise minimum value between two input arrays or matrices.
- np.minimum.reduce: This function applies the ufunc "minimum" to all elements of an input array or matrix along a given axis and returns the minimum value.
- np.max: This function returns the maximum value of an array or matrix.
- np.amax: This function returns the maximum value of an array or matrix along a given axis.
- np.maximum: This function returns an array or matrix with the element-wise maximum value between two input arrays or matrices.
- np.maximum.reduce: This function applies the ufunc "maximum" to all elements of an input array or matrix along a given axis and returns the maximum value.


In [ ]:
# Examples
matrix_A = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
print("Matrix A: \n",matrix_A)
print("Minimum value using np.min: ",np.min(matrix_A))
print("Minimum value using np.amin along axis 0: ",np.amin(matrix_A, axis=0))
print("Minimum value using np.amin along axis 1: ",np.amin(matrix_A, axis=1))
print("Minimum value using np.minimum.reduce: ",np.minimum.reduce(matrix_A))
print("Maximum value using np.max: ",np.max(matrix_A))
print("Maximum value using np.amax along axis 0: ",np.amax(matrix_A, axis=0))
print("Maximum value using np.amax along axis 1: ",np.amax(matrix_A, axis=1))
print("Maximum value using np.maximum.reduce: ",np.maximum.reduce(matrix_A))

### Covariance and correlation
- Covariance and correlation are two commonly used measures of the relationship between two variables.
- Covariance measures the degree to which two variables are linearly related. A positive covariance indicates that the variables are positively correlated, while a negative covariance indicates that the variables are negatively correlated. The function np.cov() in NumPy can be used to calculate the covariance matrix between two or more variables.


In [30]:
matrix_A = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
cov_matrix = np.cov(matrix_A)
print("Covariance matrix of matrix_A : \n",cov_matrix)

Covariance matrix of matrix_A : 
 [[ 1.5 -2.   2. ]
 [-2.   7.7 -7. ]
 [ 2.  -7.   8.5]]


- Correlation, on the other hand, is a normalized measure of the relationship between two variables. It ranges from -1 to 1, with -1 indicating a perfect negative correlation, 0 indicating no correlation, and 1 indicating a perfect positive correlation. The function np.corrcoef() in NumPy can be used to calculate the correlation matrix between two or more variables.

In [ ]:
matrix_A = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
corr_matrix = np.corrcoef(matrix_A)
print("Correlation matrix of matrix_A : \n",corr_matrix)

- In the above example, the function np.cov() returns the covariance matrix of matrix_A and the function np.corrcoef() returns the correlation matrix of matrix_A.

### What’s a NAN in numpy :
In the NumPy library, "NaN" stands for "Not a Number." It is a special value that is used to represent missing or undefined data. For example, if you try to calculate the square root of a negative number, the result will be "NaN."
Here's an example of how you might use "NaN" in a NumPy array:


In [ ]:
# create an array with some values
a = np.array([1, 2, 3, 4, 5])

In [ ]:
# set the second element to NaN
a[1] = np.nan
print(a)