## NumPy is a fundamental package for scientific computing in Python.
- It provides support for large multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

## NumPy Basics

### Importing NumPy
- NumPy is usually imported under the alias 'np'.

In [2]:
import numpy as np

### Creating Arrays
- NumPy arrays can be created from Python lists or tuples using the array() function.

In [3]:
array_from_list = np.array([1, 2, 3, 4, 5])
print(array_from_list)

[1 2 3 4 5]


In [4]:
# Creating arrays with specific values
zeros_array = np.zeros(5)  # Array of zeros
ones_array = np.ones(5)  # Array of ones
full_array = np.full(5, 7)  # Array of sevens
print(zeros_array, ones_array, full_array)

[0. 0. 0. 0. 0.] [1. 1. 1. 1. 1.] [7 7 7 7 7]


In [5]:
# Practice Questions:
# 1. Create a NumPy array from a list of numbers [10, 20, 30, 40, 50].
# 2. Create a NumPy array of ten zeros.
# 3. Create a NumPy array of five ones.

In [6]:
import numpy as np
array_of_list = np.array([10, 20, 30, 40, 50])
zeros_array = np.zeros(10)
array_of_ones = np.ones(5)
print(array_of_list,zeros_array,array_of_ones)

[10 20 30 40 50] [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [1. 1. 1. 1. 1.]


## NumPy Fundamentals

### Array Attributes
- NumPy arrays have attributes such as shape, size, and ndim.

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # Output: (2, 3)
print(arr.size)  # Output: 6
print(arr.ndim)  # Output: 2

(2, 3)
6
2


### Array Indexing and Slicing
- You can index and slice NumPy arrays just like Python lists.

In [5]:
print(arr[0, 1])  # Output: 2 (element at row 0, column 1)
print(arr[:, 1])  # Output: [2, 5] (all rows, column 1)
print(arr[1, :])  # Output: [4, 5, 6] (row 1, all columns)

2
[2 5]
[4 5 6]


In [ ]:
# Practice Questions:
# 1. Create a 3x3 NumPy array and print its shape, size, and number of dimensions.
# 2. Print the element at the second row and third column of the array.
# 3. Slice the array to get the first two columns.

In [20]:
import numpy as np
array = np.array([[[3,4,5],[6,7,8],[9,10,11]]])
print(array.shape)
print(array.size)
print(array.ndim)
print(array[0, 1, 2])
print(array[:, :, :2])

(1, 3, 3)
9
3
8
[[[ 3  4]
  [ 6  7]
  [ 9 10]]]


## Working with Arrays

In [1]:
# Basic Operations
# You can perform element-wise operations on NumPy arrays.

In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  # Output: [5, 7, 9]
print(a * b)  # Output: [4, 10, 18]
print(a - b)  # Output: [-3, -3, -3]
print(a / b)  # Output: [0.25, 0.4, 0.5]

[5 7 9]
[ 4 10 18]
[-3 -3 -3]
[0.25 0.4  0.5 ]


In [22]:
# Mathematical Functions
# NumPy provides a variety of mathematical functions.
print(np.sin(a))  # Output: [0.8415, 0.9093, 0.1411]
print(np.log(a))  # Output: [0., 0.6931, 1.0986]
print(np.sqrt(a))  # Output: [1., 1.4142, 1.7321]

[0.84147098 0.90929743 0.14112001]
[0.         0.69314718 1.09861229]
[1.         1.41421356 1.73205081]


In [ ]:
# Practice Questions:
# 1. Create two NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
# 2. Apply the numpy functions sin(), log(), and sqrt() to a NumPy array.

In [23]:
import numpy as np
a = np.array([3,4,5])
b = np.array([9,5,2])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(np.sin(b))
print(np.log(b))
print(np.sqrt(b))

[12  9  7]
[-6 -1  3]
[27 20 10]
[0.33333333 0.8        2.5       ]
[ 0.41211849 -0.95892427  0.90929743]
[2.19722458 1.60943791 0.69314718]
[3.         2.23606798 1.41421356]


### Generating Data with NumPy

- Creating arrays with arange() and linspace()
- The arange() function generates an array with a range of values.


In [24]:
range_array = np.arange(0, 10, 2)  # Start, stop, step
print(range_array)  # Output: [0, 2, 4, 6, 8]

[0 2 4 6 8]


In [25]:
# The linspace() function generates an array with evenly spaced values.
linspace_array = np.linspace(0, 1, 5)  # Start, stop, number of points
print(linspace_array)  # Output: [0., 0.25, 0.5, 0.75, 1.]

[0.   0.25 0.5  0.75 1.  ]


In [26]:
# Generating random numbers
random_array = np.random.random((2, 3))  # 2x3 array of random numbers between 0 and 1
print(random_array)

[[0.85985867 0.48547132 0.88629559]
 [0.69543608 0.6411744  0.66507651]]


In [ ]:
# Practice Questions:
# 1. Create an array of numbers from 0 to 20 with a step of 5 using arange().
# 2. Create an array of 10 numbers evenly spaced between 0 and 1 using linspace().
# 3. Generate a 3x3 array of random numbers between 0 and 1.

In [29]:
import numpy as np
array = np.arange(0, 20, 5)
array_1 = np.linspace(0, 1, 10)
array_2 = np.random.random((3, 3))

print(array, array_1, array_2)

[ 0  5 10 15] [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ] [[0.2809247  0.94884055 0.47172362]
 [0.28714175 0.05521619 0.011348  ]
 [0.3117295  0.6399955  0.55046684]]


### Statistics with NumPy

- NumPy provides various statistical functions to analyze data.

In [ ]:
data = np.array([1, 2, 3, 4, 5])

# Mean, median, and standard deviation
mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)
print("Mean:", mean)  # Output: Mean: 3.0
print("Median:", median)  # Output: Median: 3.0
print("Standard Deviation:", std_dev)  # Output: Standard Deviation: 1.4142

In [ ]:
# Sum and cumulative sum
sum_data = np.sum(data)
cumsum_data = np.cumsum(data)
print("Sum:", sum_data)  # Output: Sum: 15
print("Cumulative Sum:", cumsum_data)  # Output: Cumulative Sum: [ 1  3  6 10 15]

In [ ]:
# Practice Questions:
# 1. Create a NumPy array of random numbers and compute the mean, median, and standard deviation.
# 2. Compute the sum and cumulative sum of the array.

In [ ]:
import numpy as np
data = np.array([3,4,5,8,9])
mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)
sum_data = np.sum(data)
cumsum_data = np.cumsum(data)

print('Mean:', mean)
print('Median:', median)
print('Standard deviation:', std_dev)
print('Sum:', sum_data)
print('cumulative sum:', cumsum_data)